# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.7
repos:
-   repo: local
    hooks:
    -   id: sphinx
        name: build sphinx docs
        language: system
        entry: bash -c 'sphinx-build -b html docs_src docs || true'